### ISSUE TITLE
Unable to use fakettp install

### ISSUE THREAD

**Issue by alkesh** [kerryb/fakettp#1]
fakettp_command needs to require both 'fileutils' and 'active_support',
otherwise it fails to create the directory,
or it fails to 'to_yaml' a Hash.

**Comment by kerryb** [comment]
Believed fixed in 72eeff0002d1300d270ea04a704ff4f762ff5dfb

Updated gem released as 0.3.8

**Comment by kerryb** [comment]
Closed
